// Generated by CoffeeScript 1.4.0
(function() {
  var User,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $(function() {
    var Checkurl, isFocused, isNew, magic, msgSound, old, sendSound, title, user, whereami;
    title = '';
    isFocused = true;
    isNew = false;
    magic = {
      'WTF': 'img/wtf.jpg',
      'FUCK': 'img/fuck.gif',
      'SUP': 'img/sup.jpg',
      'LOL': 'img/lol.jpg',
      'OOPS': 'img/oops.jpeg',
      'XIXI': 'img/xixi.jpeg',
      'HEIHEI': 'img/heihei.png',
      'CONGRATS': 'img/congrats.jpg',
      '...': 'img/nocomments.jpg',
      'LTYC': 'img/ltyc.jpeg',
      'WHAT??!!': 'img/what.jpg',
      'BUT WHY?': 'img/butwhy.jpeg',
      'THX': 'img/thx.jpeg'
    };
    user = null;
    sendSound = document.getElementById('sendAudio');
    msgSound = document.getElementById('msgAudio');
    old = '';
    $('#chat_main_table').hide();
    $('#homepage_input_id').focus();
    $('.pick_table').hide();
    $('#homepage_button').click(function() {
      var source;
      if ($('#homepage_input_id').val() === '' || $('#homepage_input_session').val() === '') {
        alert('Incomplete user input.');
        return;
      }
      $('#chat_main_table').show();
      $('#msg_input').focus();
      user = new User($('#homepage_input_id').val(), $('#homepage_input_session').val());
      document.title = user.getId() + '@' + user.getSession() + ' -- WebMsg';
      title = document.title;
      source = new EventSource('php/sse.php?session=' + user.getSession());
      return source.onmessage = function(event) {
        if (event.data !== old) {
          if (!isFocused) {
            isNew = true + title;
          }
          msgSound.play();
          old = event.data;
          $('#msg_div').html(old);
          return $('#msg_div').scrollTop($('#msg_div')[0].scrollHeight);
        }
      };
    });
    $('#msg_input_button').click(function() {
      var msg, value;
      if ($('#msg_input').val() === '') {
        return;
      }
      if ($('#msg_input').val() === 'whereami') {
        $('#msg_input').val(whereami());
        return;
      }
      if ((value = magic[$('#msg_input').val().toUpperCase()]) != null) {
        msg = encodeURIComponent(Checkurl('img:' + value));
      } else {
        msg = encodeURIComponent(Checkurl($('#msg_input').val()));
      }
      $('#msg_input').val('');
      return $.ajax({
        url: 'php/send.php?user=' + user.getId() + '&session=' + user.getSession() + '&msg=' + msg
      });
    });
    $('#homepage_input_id, #homepage_input_session').keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
        return $('#homepage_button').click();
      }
    });
    $('#msg_input').keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
        return $('#msg_input_button').click();
      }
    });
    $('#msg_div').click(function() {
      return $.ajax({
        url: 'php/all.php?session=' + user.getSession()
      }).done(function(msg) {
        $('.pick_table').show();
        $('#pick_div').html(msg);
        return $('#pick_div').scrollTop($('#pick_div')[0].scrollHeight);
      });
    });
    $('.pick_td, .pick_tr').click(function() {
      $('#pick_div').html('');
      return $('.pick_table').hide();
    });
    $('#mute_box').change(function() {
      var element;
      element = document.getElementById('mute_box');
      if (element.checked === true) {
        msgSound.muted = true;
      }
      if (element.checked === false) {
        return msgSound.muted = false;
      }
    });
    $([window, document]).focusin(function() {
      document.title = title;
      isFocused = true;
      isNew = false;
      return msgSound.muted = true;
    }).focusout(function() {
      isFocused = false;
      if (document.getElementById('mute_box').checked === false) {
        msgSound.muted = false;
      }
      if (document.getElementById('mute_box').checked === true) {
        return msgSound.muted = true;
      }
    });
    whereami = function() {
      return user.getSession();
    };
    setInterval(function() {
      if (!(user != null)) {
        return;
      }
      if (!isFocused && isNew) {
        if (document.title === title) {
          return document.title = 'New Message';
        } else {
          return document.title = title;
        }
      }
    }, 1000);
    return Checkurl = function(text) {
      var html, url1, url2, url3;
      url1 = /(^|&lt;|\s)(www\..+?\..+?)(\s|&gt;|$)/g;
      url2 = /(^|&lt;|\s)(((https?|ftp):\/\/|mailto:).+?)(\s|&gt;|$)/g;
      url3 = /(^|&lt;|\s)(img\:.+?\..+?)(\s|&gt;|$)/g;
      html = $.trim(text);
      if (html) {
        html = html.replace(url1, '$1<a style="color:blue; text-decoration:underline;" target="_blank"  href="http://$2">$2</a>$3').replace(url2, '$1<a style="color:blue; text-decoration:underline;" target="_blank"  href="$2">$2</a>$5').replace(url3, '$1<img width="100%" src="$2"/>&nbsp;$3').replace(/src=\"img\:/g, 'src="');
      }
      return html;
    };
  });

  User = (function() {

    function User(id, session) {
      this.id = id;
      this.session = session;
      this.getSession = __bind(this.getSession, this);

      this.setSession = __bind(this.setSession, this);

      this.getId = __bind(this.getId, this);

      this.setId = __bind(this.setId, this);

    }

    User.prototype.setId = function(id) {
      return this.id = id;
    };

    User.prototype.getId = function() {
      return this.id;
    };

    User.prototype.setSession = function(session) {
      return this.session = session;
    };

    User.prototype.getSession = function() {
      return this.session;
    };

    return User;

  })();

}).call(this);
