// Generated by CoffeeScript 1.4.0
(function() {
  var User,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $(function() {
    var Checkurl, GLOBAL_PUBLIC, barrelRoll, brightScreen, color, darkScreen, getRandomColor, gradient, isColor, isFocused, isGradient, isNew, magic, msgSound, old, rolled, sendSound, showHistory, title, user, whereami, whoami;
    GLOBAL_PUBLIC = 'public';
    rolled = false;
    title = 'WebMsg';
    isFocused = true;
    isNew = false;
    isColor = false;
    isGradient = false;
    color = '';
    gradient = '';
    magic = {
      'BATMAN': 'img/batman.gif',
      'HOLY JESUS': 'img/jesus.jpg',
      'WHAT?!': 'img/what_bang.jpg',
      'HELLO WORLD': 'img/hello-world.jpg',
      'WHY YOU\'RE SO COOL': 'img/why_so_cool.jpg',
      'WHY YOU\'RE SO COOL?': 'img/why_so_cool.jpg',
      'HOHO': 'img/ho-ho-ho.jpg',
      'SOUNDS GOOD': 'img/sounds-good.jpg',
      'YOU\'RE SO COOL': 'img/youre-so-cool.jpg',
      'VERY NICE': 'img/very_nice.jpg',
      'YOU ROCK': 'img/you_rock.png',
      'HEY BOY': 'img/hey_boy.jpg',
      'SIMPLES': 'img/simples.jpg',
      'AH I SEE': 'img/I_c.jpg',
      'NEVER MIND': 'img/never_mind.jpeg',
      'OH YOU\'RE COOL': 'img/oh-you-re-cool.jpg',
      'YOU\'RE COOL': 'img/oh-you-re-cool.jpg',
      'DEAL WITH IT': 'img/deal_with_it.jpg',
      'CRYING': 'img/cry.png',
      'HEY YOU\'RE AWESOME': 'img/awesome.jpg',
      'YOU\'RE AWESOME': 'img/awesome.jpg',
      'HEY GIRL': 'img/hey_girl.jpg',
      'OMG, ARE YOU OK?': 'img/omg_okay.jpeg',
      'OMG ARE YOU OK?': 'img/omg_okay.jpeg',
      'OMG ARE YOU OK': 'img/omg_okay.jpeg',
      'OMG, ARE YOU OK?': 'img/omg_okay.jpeg',
      'WELL DONE': 'img/well_done.jpg',
      'OH WELL': 'img/oh_well.jpg',
      'THUMBS UP': 'img/thumbs_up.jpg',
      'BEING IGNORED': 'img/ignored.png',
      'AHAHA': 'img/ahaha.jpeg',
      'WAZZ UP': 'img/Orange.jpg',
      'THUMB UP': 'img/thumb_up.jpg',
      '!!!': 'img/angry.png',
      'NOT GOOD': 'img/notgood.png',
      'THAT\'S COOL': 'img/cool.jpg',
      'WTF': 'img/wtf_bean.jpg',
      'FUCK': 'img/fuck.gif',
      'SUP': 'img/sup.jpg',
      'LOL': 'img/lol.jpg',
      'OOPS': 'img/oops.jpeg',
      'XIXI': 'img/xixi.jpeg',
      'HEIHEI': 'img/heihei.png',
      'CONGRATS': 'img/congrats.jpg',
      '...': 'img/nocomments.jpg',
      'LTYC': 'img/ltyc.jpeg',
      'WHAT??!!': 'img/what.jpg',
      'BUT WHY?': 'img/butwhy.jpeg',
      'THX': 'img/thx.jpeg',
      'HAHA': 'img/haha.gif',
      'HAHAHA': 'img/haha_yao.jpg',
      'SO FUNNY': 'img/so-funny.jpg',
      'NO!': 'img/no.jpg',
      'NOT BAD': 'img/not_bad_1.jpeg'
    };
    user = null;
    sendSound = document.getElementById('sendAudio');
    msgSound = document.getElementById('msgAudio');
    old = '';
    $('#chat_main_table').hide();
    $('#homepage_input_id').focus();
    $('.pick_table').hide();
    $('#homepage_button').click(function() {
      var source;
      if ($('#homepage_input_id').val() === '') {
        alert('Please enter your nickname.');
        return;
      }
      if ($('#homepage_input_session').val() === '') {
        $('#homepage_input_session').val(GLOBAL_PUBLIC);
      }
      $('.main-container').css("visibility", "visible");
      $('#msg_input').focus();
      user = new User($('#homepage_input_id').val(), $('#homepage_input_session').val());
      $('#homepage_output').css("background-color", "white");
      $('#homepage_output').html('');
      document.title = 'WebMsg';
      title = document.title;
      source = new EventSource('php/sse.php?session=' + user.getSession());
      return source.onmessage = function(event) {
        if (event.data !== old) {
          if (!isFocused && old !== '') {
            isNew = true;
          }
          if (event.data === 'do a barrel roll') {
            $('#msg_div').html(old);
            if (rolled === false) {
              barrelRoll();
              rolled = true;
            }
            return;
          }
          rolled = false;
          if (old !== '') {
            msgSound.play();
          }
          old = event.data;
          // old = old.replace(/\'/g, '\\\'');
          $('#msg_div').html(old);
          return $('#msg_div').scrollTop($('#msg_div')[0].scrollHeight);
        }
      };
    });
    $('#msg_input_button').click(function() {
      var ca, cb, msg, value;
      if ($('#msg_input').val() === '') {
        return;
      }
      if ($('#msg_input').val() === 'brightscreen') {
        $('#msg_input').val('');
        brightScreen();
        return;
      }
      if ($('#msg_input').val() === 'barrelroll') {
        $('#msg_input').val('');
        barrelRoll();
        return;
      }
      if ($('#msg_input').val() === 'showmehistory') {
        $('#msg_input').val('');
        showHistory();
        return;
      }
      if ($('#msg_input').val() === 'whereami') {
        $('#msg_input').val(whereami());
        return;
      }
      if ($('#msg_input').val() === 'whoami') {
        $('#msg_input').val(whoami());
        return;
      }
      if ($('#msg_input').val() === 'colorme' || $('#msg_input').val() === 'colourme') {
        isGradient = false;
        isColor = true;
        color = getRandomColor();
        $('#msg_input').val('');
        return;
      }
      if ($('#msg_input').val() === 'nocolor' || $('#msg_input').val() === 'nocolour') {
        isColor = false;
        color = '';
        $('#msg_input').val('');
        return;
      }
      if ($('#msg_input').val() === 'gradient') {
        isColor = false;
        isGradient = true;
        ca = getRandomColor();
        cb = getRandomColor();
        gradient = 'style="background:' + 'linear-gradient(' + ca + ', ' + cb + '); background-clip: text; text-fill-color: transparent;' + 'background: -webkit-linear-gradient(' + ca + ', ' + cb + '); -webkit-background-clip: text; -webkit-text-fill-color: transparent;' + 'background: -moz-linear-gradient(' + ca + ', ' + cb + '); -moz-background-clip: text; -moz-text-fill-color: transparent;' + '-ie-background: linear-gradient(' + ca + ', ' + cb + '); -ie-background-clip: text; -ie-text-fill-color: transparent;' + '-o-background: linear-gradient(' + ca + ', ' + cb + '); -o-background-clip: text; -o-text-fill-color: transparent;' + '"';
        $('#msg_input').val('');
        return;
      }
      if ($('#msg_input').val() === 'nogradient') {
        isGradient = false;
        gradient = '';
        $('#msg_input').val('');
        return;
      }
      if ((value = magic[$('#msg_input').val().toUpperCase()]) != null) {
        msg = encodeURIComponent(Checkurl('img:' + value));
      } else {
        if (!isColor && !isGradient) {
          msg = encodeURIComponent(Checkurl($('#msg_input').val()));
        }
        if (isColor) {
          msg = Checkurl($('#msg_input').val());
          msg = encodeURIComponent('<div class="shadow_text" style="color: ' + color + '">' + msg + '</div>');
        } else if (isGradient) {
          msg = Checkurl($('#msg_input').val());
          msg = msg.replace(/\'/g, '\\\'');
          msg = encodeURIComponent('<div ' + gradient + '>' + msg + '</div>');
        }
      }
      msg = msg.replace(/\'/g, '\\\'');
      $('#msg_input').val('');
      return $.ajax({
        url: 'php/send.php?user=' + user.getId() + '&session=' + user.getSession() + '&msg=' + msg
      });
    });
    $('#homepage_input_id, #homepage_input_session').keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
        return $('#homepage_button').click();
      }
    });
    $('#msg_input').keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
        return $('#msg_input_button').click();
      }
    });
    $('.pick_td, .pick_tr').click(function() {
      $('#pick_div').html('');
      return $('.pick_table').hide();
    });
    $('#mute_box').change(function() {
      var element;
      element = document.getElementById('mute_box');
      if (element.checked === true) {
        msgSound.muted = true;
      }
      if (element.checked === false) {
        return msgSound.muted = false;
      }
    });
    $([window, document, 'table', 'input']).focusin(function() {
      document.title = title;
      isFocused = true;
      isNew = false;
      return msgSound.muted = true;
    }).focusout(function() {
      isFocused = false;
      if (document.getElementById('mute_box').checked === false) {
        msgSound.muted = false;
      }
      if (document.getElementById('mute_box').checked === true) {
        return msgSound.muted = true;
      }
    });
    $('*').click(function() {
      isFocused = true;
      return msgSound.muted = true;
    });
    whereami = function() {
      return user.getSession();
    };
    whoami = function() {
      return user.getId();
    };
    setInterval(function() {
      if (!(user != null)) {
        return;
      }
      if (!isFocused && isNew) {
        if (document.title === title) {
          return document.title = 'New Message';
        } else {
          return document.title = title;
        }
      }
    }, 1000);
    Checkurl = function(text) {
      var html, url1, url2, url3;
      url1 = /(^|&lt;|\s)(www\..+?\..+?)(\s|&gt;|$)/g;
      url2 = /(^|&lt;|\s)(((https?|ftp):\/\/|mailto:).+?)(\s|&gt;|$)/g;
      url3 = /(^|&lt;|\s)(img\:.+?\..+?)(\s|&gt;|$)/g;
      html = $.trim(text);
      if (html) {
        html = html.replace(url1, '$1<a style="color:blue; text-decoration:underline;" target="_blank"  href="http://$2">$2</a>$3').replace(url2, '$1<a style="color:blue; text-decoration:underline;" target="_blank"  href="$2">$2</a>$5').replace(url3, '$1<img src="$2"/>&nbsp;$3').replace(/src=\"img\:/g, 'src="');
      }
      return html;
    };
    getRandomColor = function() {
      var i, letters, _i;
      letters = '0123456789ABCDEF'.split('');
      color = '#';
      for (i = _i = 0; _i <= 5; i = ++_i) {
        color += letters[Math.round(Math.random() * 15)];
      }
      return color;
    };
    showHistory = function() {
      return $.ajax({
        url: 'php/all.php?session=' + user.getSession()
      }).done(function(msg) {
        $('.pick_table').show();
        $('#pick_div').html(msg);
        return $('#pick_div').scrollTop($('#pick_div')[0].scrollHeight);
      });
    };
    barrelRoll = function() {
      $('.main-container').addClass('barrel_roll');
      return setTimeout(function() {
        return $('.chat_main_table').removeClass('barrel_roll');
      }, 4000);
    };
    darkScreen = function() {
      $('*').css('background', 'black');
      return $('input, label').css({
        'border': 'none',
        'color': 'white'
      });
    };
    return brightScreen = function() {
      $('*').css('background', 'white');
      $('input').css({
        'border': 'thin solid grey',
        'color': 'black'
      });
      return $('label').css({
        'color': 'black'
      });
    };
  });

  User = (function() {

    function User(id, session) {
      this.id = id;
      this.session = session;
      this.getSession = __bind(this.getSession, this);

      this.setSession = __bind(this.setSession, this);

      this.getId = __bind(this.getId, this);

      this.setId = __bind(this.setId, this);

    }

    User.prototype.setId = function(id) {
      return this.id = id;
    };

    User.prototype.getId = function() {
      return this.id;
    };

    User.prototype.setSession = function(session) {
      return this.session = session;
    };

    User.prototype.getSession = function() {
      return this.session;
    };

    return User;

  })();

}).call(this);
